title: Raúl Bejarano
cv:
    name: Raúl
    surname: Bejarano
    email: raul.bejarano.parrilla@gmail.com
    phone: 
    city: Bilbao
    country: Spain
    social:
        facebook: raul.bejarano.735
        twitter:  rbejarano_
        linkedin:  raul-bejarano
        github:  RaulBejarano

# Build settings
permalink: :title/
sass:
    sass_dir: css
